[project]
name = "pacman"
version = "0.0.1"
description = "Ghosts! More ghosts!"
requires-python = ">=3.12"
dependencies = [
    "mazegenerator",
]

[dependency-groups]
dev = [
    "flake8",
    "mypy",
]

[tool.mypy]
explicit_package_bases = true
mypy_path = "src"

[tool.uv.sources]
mazegenerator = { path = "mazegenerator-2.1.0-py3-none-any.whl" }
